### ISSUE TITLE
Does not compile with c11 standards.

### ISSUE THREAD

**Issue by TimJSwan89** [calccrypto/tar#1]
One may compile if the `-std=c11` flag is removed from the `Makefile`.

```
tar.c:551:26: error: ‘S_IFMT’ undeclared (first use in this function)
     switch (st.st_mode & S_IFMT) {
```

Also applies with {`S_IFREG`, `S_IFLINK`, `S_IFCHR`, `S_IFBLK`, `S_IFDIR`, `S_IFIFO`, `S_IFSOCK`}

**Comment by calccrypto** [comment]
That is strange, since these are POSIX definitions, not C11. It was fixed by [defining _BSD_SOURCE](49ff34bc6965de7cdd60f75eef32ff01d7479857)
