### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by calccrypto** [calccrypto/tar#3]

**Comment by zwykl3** [comment]
```
./tar.h:41:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [tar.o] Error 1
```

**Comment by calccrypto** [comment]
@zwykl3 What system are you compiling on?

**Comment by zwykl3** [comment]
```
$ uname -a
Darwin dupa.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
on linux arm i compile lib bud exe have trouble

```
$./exec
Naruszenie ochrony pamięci
$uname
Linux jamajka 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux
```

**Comment by calccrypto** [comment]
I am afraid I do not work with OSX very much, and do not have any machine with OSX on hand to compile on. Try removing the line `#include <sys/sysmacros.h>`. It seems that `major` and `minor` are defined in [`sys/types.h`](https://opensource.apple.com/source/xnu/xnu-201/bsd/sys/types.h.auto.html) in OSX.

As for the segmentations fault, please provide a trace of the execution stack.
