### ISSUE TITLE
No error is shown when removing nonexistent file from archive

### ISSUE THREAD

**Issue by mimi89999** [calccrypto/tar#6]
Hello,
When I remove a nonexistent file from an archive, I get _Exiting with error due to previous error_ but no other errors are shown:
```
$ touch test1 test2 test3
$ tar -cf test.tar test1 test2 test3
$ exec r test.tar test4
Exiting with error due to previous error
```

**Comment by calccrypto** [comment]
5f5cd94ee2658e1c511502380ee961adf1544697 should fix this.
